run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - errorlint
    - exhaustive
    - copyloopvar
    - gochecknoinits
    - goconst
    - gocyclo
    - godot
    - gofmt
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nilerr
    - noctx
    - nolintlint
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unused
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    # Disable check-blank to avoid false positives on intentionally ignored errors.
    check-blank: false

  errorlint:
    errorf: true

  exhaustive:
    default-signifies-exhaustive: true

  gocyclo:
    min-complexity: 20

  goconst:
    min-len: 3
    min-occurrences: 3

  gofmt:
    simplify: true

  goimports:
    local-prefixes: factory

  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: superfluous-else
      - name: unreachable-code
      - name: redefines-builtin-id

  staticcheck:
    checks: ["all"]

  stylecheck:
    checks: ["all", "-ST1000", "-ST1003"]

issues:
  exclude-rules:
    # Exclude test files from some checks.
    - path: _test\.go
      linters:
        - errcheck
        - goconst
        - gosec

    # Exclude main packages from package comment check.
    - path: cmd/
      linters:
        - revive
      text: "package-comments"

    # Allow blank imports in main package for driver registration.
    - path: agents/rag/store\.go
      linters:
        - revive
      text: "blank-imports"

  max-issues-per-linter: 50
  max-same-issues: 5
